---
# LEAF1 specific data model

# Interfaces

interfaces:
  Ethernet1:
    descr: "To_Spine1"
    mode: "trunk"
  Ethernet2:
    descr: "To_Spine2"
    mode: "trunk"
  Ethernet10:
    descr: "Host1"
    mode: "access"
    vlan: 10
  Ethernet48:
    descr: "To_Leaf2"
    mode: "trunk"


# VLANs


